apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: charan-task
spec:
  params:
    - name: repository
      description: The git repo
    - name: branch
      description: the branch for the git repo
  steps:
    - name: noshebang
      image: ubuntu
      script: echo "no shebang"
    - name: printrepo
      image: ubuntu
      script: echo "no shebang"
byrnedo/alpine-curl
    - name: echo
      image: ubuntu
      command:
        - echo
      args:
        - "hello charan"
    - name: kubectl-commandss
      image: widerin/openshift-cli
      stage: deploy
      script:
        - oc login --token=IAnpGQPE3h8AclTAIrDd_G58fGVOC050VoPhy9049s4 --server=https://c106-e.us-south.containers.cloud.ibm.com:31711
        - oc projects
