apiVersion: tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: charan-trigger-template
spec:
  params:
    - name: repository
      description: The git repo
    - name: branch
      description: the branch for the git repo
  resourcetemplates:
    - apiVersion: tekton.dev/v1alpha1
      kind: PipelineRun
      metadata:
        name: charan-pipelinerun-$(uid)
      spec:
        pipelineRef:
          name: charan-pipeline
        params:
          - name: repository
            value: $(params.repository)
          - name: branch
            value: $(params.branch)
